// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/grpc_remote.proto

package org.urbcomp.cupid.db.spark.data;

public final class GrpcRemote {
  private GrpcRemote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SchemaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.urbcomp.cupid.db.spark.data.SchemaRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sqlId = 1;</code>
     */
    boolean hasSqlId();
    /**
     * <code>required string sqlId = 1;</code>
     */
    java.lang.String getSqlId();
    /**
     * <code>required string sqlId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSqlIdBytes();

    /**
     * <code>required string schemaJson = 2;</code>
     */
    boolean hasSchemaJson();
    /**
     * <code>required string schemaJson = 2;</code>
     */
    java.lang.String getSchemaJson();
    /**
     * <code>required string schemaJson = 2;</code>
     */
    com.google.protobuf.ByteString
        getSchemaJsonBytes();
  }
  /**
   * Protobuf type {@code org.urbcomp.cupid.db.spark.data.SchemaRequest}
   */
  public  static final class SchemaRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.urbcomp.cupid.db.spark.data.SchemaRequest)
      SchemaRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SchemaRequest.newBuilder() to construct.
    private SchemaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SchemaRequest() {
      sqlId_ = "";
      schemaJson_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SchemaRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sqlId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              schemaJson_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SQLID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sqlId_;
    /**
     * <code>required string sqlId = 1;</code>
     */
    public boolean hasSqlId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sqlId = 1;</code>
     */
    public java.lang.String getSqlId() {
      java.lang.Object ref = sqlId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sqlId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sqlId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSqlIdBytes() {
      java.lang.Object ref = sqlId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEMAJSON_FIELD_NUMBER = 2;
    private volatile java.lang.Object schemaJson_;
    /**
     * <code>required string schemaJson = 2;</code>
     */
    public boolean hasSchemaJson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string schemaJson = 2;</code>
     */
    public java.lang.String getSchemaJson() {
      java.lang.Object ref = schemaJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          schemaJson_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string schemaJson = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSchemaJsonBytes() {
      java.lang.Object ref = schemaJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schemaJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSqlId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSchemaJson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sqlId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, schemaJson_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sqlId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, schemaJson_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest)) {
        return super.equals(obj);
      }
      org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest other = (org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest) obj;

      boolean result = true;
      result = result && (hasSqlId() == other.hasSqlId());
      if (hasSqlId()) {
        result = result && getSqlId()
            .equals(other.getSqlId());
      }
      result = result && (hasSchemaJson() == other.hasSchemaJson());
      if (hasSchemaJson()) {
        result = result && getSchemaJson()
            .equals(other.getSchemaJson());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSqlId()) {
        hash = (37 * hash) + SQLID_FIELD_NUMBER;
        hash = (53 * hash) + getSqlId().hashCode();
      }
      if (hasSchemaJson()) {
        hash = (37 * hash) + SCHEMAJSON_FIELD_NUMBER;
        hash = (53 * hash) + getSchemaJson().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.urbcomp.cupid.db.spark.data.SchemaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.urbcomp.cupid.db.spark.data.SchemaRequest)
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.Builder.class);
      }

      // Construct using org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sqlId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        schemaJson_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest getDefaultInstanceForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest build() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest buildPartial() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest result = new org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sqlId_ = sqlId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.schemaJson_ = schemaJson_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest) {
          return mergeFrom((org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest other) {
        if (other == org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest.getDefaultInstance()) return this;
        if (other.hasSqlId()) {
          bitField0_ |= 0x00000001;
          sqlId_ = other.sqlId_;
          onChanged();
        }
        if (other.hasSchemaJson()) {
          bitField0_ |= 0x00000002;
          schemaJson_ = other.schemaJson_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSqlId()) {
          return false;
        }
        if (!hasSchemaJson()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sqlId_ = "";
      /**
       * <code>required string sqlId = 1;</code>
       */
      public boolean hasSqlId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public java.lang.String getSqlId() {
        java.lang.Object ref = sqlId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sqlId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSqlIdBytes() {
        java.lang.Object ref = sqlId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sqlId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder setSqlId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sqlId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder clearSqlId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sqlId_ = getDefaultInstance().getSqlId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder setSqlIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sqlId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object schemaJson_ = "";
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public boolean hasSchemaJson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public java.lang.String getSchemaJson() {
        java.lang.Object ref = schemaJson_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            schemaJson_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSchemaJsonBytes() {
        java.lang.Object ref = schemaJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schemaJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public Builder setSchemaJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        schemaJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public Builder clearSchemaJson() {
        bitField0_ = (bitField0_ & ~0x00000002);
        schemaJson_ = getDefaultInstance().getSchemaJson();
        onChanged();
        return this;
      }
      /**
       * <code>required string schemaJson = 2;</code>
       */
      public Builder setSchemaJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        schemaJson_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.urbcomp.cupid.db.spark.data.SchemaRequest)
    }

    // @@protoc_insertion_point(class_scope:org.urbcomp.cupid.db.spark.data.SchemaRequest)
    private static final org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest();
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SchemaRequest>
        PARSER = new com.google.protobuf.AbstractParser<SchemaRequest>() {
      @java.lang.Override
      public SchemaRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchemaRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SchemaRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SchemaRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SchemaResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.urbcomp.cupid.db.spark.data.SchemaResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string res = 1;</code>
     */
    boolean hasRes();
    /**
     * <code>optional string res = 1;</code>
     */
    java.lang.String getRes();
    /**
     * <code>optional string res = 1;</code>
     */
    com.google.protobuf.ByteString
        getResBytes();
  }
  /**
   * Protobuf type {@code org.urbcomp.cupid.db.spark.data.SchemaResponse}
   */
  public  static final class SchemaResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.urbcomp.cupid.db.spark.data.SchemaResponse)
      SchemaResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SchemaResponse.newBuilder() to construct.
    private SchemaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SchemaResponse() {
      res_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SchemaResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              res_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RES_FIELD_NUMBER = 1;
    private volatile java.lang.Object res_;
    /**
     * <code>optional string res = 1;</code>
     */
    public boolean hasRes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string res = 1;</code>
     */
    public java.lang.String getRes() {
      java.lang.Object ref = res_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          res_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string res = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResBytes() {
      java.lang.Object ref = res_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        res_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, res_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, res_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse)) {
        return super.equals(obj);
      }
      org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse other = (org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse) obj;

      boolean result = true;
      result = result && (hasRes() == other.hasRes());
      if (hasRes()) {
        result = result && getRes()
            .equals(other.getRes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRes()) {
        hash = (37 * hash) + RES_FIELD_NUMBER;
        hash = (53 * hash) + getRes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.urbcomp.cupid.db.spark.data.SchemaResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.urbcomp.cupid.db.spark.data.SchemaResponse)
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.Builder.class);
      }

      // Construct using org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        res_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse getDefaultInstanceForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse build() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse buildPartial() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse result = new org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.res_ = res_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse) {
          return mergeFrom((org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse other) {
        if (other == org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse.getDefaultInstance()) return this;
        if (other.hasRes()) {
          bitField0_ |= 0x00000001;
          res_ = other.res_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object res_ = "";
      /**
       * <code>optional string res = 1;</code>
       */
      public boolean hasRes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string res = 1;</code>
       */
      public java.lang.String getRes() {
        java.lang.Object ref = res_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            res_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string res = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResBytes() {
        java.lang.Object ref = res_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          res_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string res = 1;</code>
       */
      public Builder setRes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        res_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string res = 1;</code>
       */
      public Builder clearRes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        res_ = getDefaultInstance().getRes();
        onChanged();
        return this;
      }
      /**
       * <code>optional string res = 1;</code>
       */
      public Builder setResBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        res_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.urbcomp.cupid.db.spark.data.SchemaResponse)
    }

    // @@protoc_insertion_point(class_scope:org.urbcomp.cupid.db.spark.data.SchemaResponse)
    private static final org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse();
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SchemaResponse>
        PARSER = new com.google.protobuf.AbstractParser<SchemaResponse>() {
      @java.lang.Override
      public SchemaResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchemaResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SchemaResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SchemaResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.urbcomp.cupid.db.spark.data.GrpcRemote.SchemaResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RowRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.urbcomp.cupid.db.spark.data.RowRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string sqlId = 1;</code>
     */
    boolean hasSqlId();
    /**
     * <code>required string sqlId = 1;</code>
     */
    java.lang.String getSqlId();
    /**
     * <code>required string sqlId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSqlIdBytes();
  }
  /**
   * Protobuf type {@code org.urbcomp.cupid.db.spark.data.RowRequest}
   */
  public  static final class RowRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.urbcomp.cupid.db.spark.data.RowRequest)
      RowRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RowRequest.newBuilder() to construct.
    private RowRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RowRequest() {
      sqlId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RowRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              sqlId_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SQLID_FIELD_NUMBER = 1;
    private volatile java.lang.Object sqlId_;
    /**
     * <code>required string sqlId = 1;</code>
     */
    public boolean hasSqlId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sqlId = 1;</code>
     */
    public java.lang.String getSqlId() {
      java.lang.Object ref = sqlId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sqlId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sqlId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSqlIdBytes() {
      java.lang.Object ref = sqlId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sqlId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSqlId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sqlId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sqlId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest)) {
        return super.equals(obj);
      }
      org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest other = (org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest) obj;

      boolean result = true;
      result = result && (hasSqlId() == other.hasSqlId());
      if (hasSqlId()) {
        result = result && getSqlId()
            .equals(other.getSqlId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSqlId()) {
        hash = (37 * hash) + SQLID_FIELD_NUMBER;
        hash = (53 * hash) + getSqlId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.urbcomp.cupid.db.spark.data.RowRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.urbcomp.cupid.db.spark.data.RowRequest)
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.Builder.class);
      }

      // Construct using org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sqlId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest getDefaultInstanceForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest build() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest buildPartial() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest result = new org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sqlId_ = sqlId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest) {
          return mergeFrom((org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest other) {
        if (other == org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest.getDefaultInstance()) return this;
        if (other.hasSqlId()) {
          bitField0_ |= 0x00000001;
          sqlId_ = other.sqlId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSqlId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object sqlId_ = "";
      /**
       * <code>required string sqlId = 1;</code>
       */
      public boolean hasSqlId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public java.lang.String getSqlId() {
        java.lang.Object ref = sqlId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sqlId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSqlIdBytes() {
        java.lang.Object ref = sqlId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sqlId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder setSqlId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sqlId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder clearSqlId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sqlId_ = getDefaultInstance().getSqlId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sqlId = 1;</code>
       */
      public Builder setSqlIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sqlId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.urbcomp.cupid.db.spark.data.RowRequest)
    }

    // @@protoc_insertion_point(class_scope:org.urbcomp.cupid.db.spark.data.RowRequest)
    private static final org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest();
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RowRequest>
        PARSER = new com.google.protobuf.AbstractParser<RowRequest>() {
      @java.lang.Override
      public RowRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RowRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RowRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RowResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.urbcomp.cupid.db.spark.data.RowResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.urbcomp.cupid.db.spark.data.RowResponse}
   */
  public  static final class RowResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.urbcomp.cupid.db.spark.data.RowResponse)
      RowResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RowResponse.newBuilder() to construct.
    private RowResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RowResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RowResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse)) {
        return super.equals(obj);
      }
      org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse other = (org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.urbcomp.cupid.db.spark.data.RowResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.urbcomp.cupid.db.spark.data.RowResponse)
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.class, org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.Builder.class);
      }

      // Construct using org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse getDefaultInstanceForType() {
        return org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse build() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse buildPartial() {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse result = new org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse) {
          return mergeFrom((org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse other) {
        if (other == org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.urbcomp.cupid.db.spark.data.RowResponse)
    }

    // @@protoc_insertion_point(class_scope:org.urbcomp.cupid.db.spark.data.RowResponse)
    private static final org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse();
    }

    public static org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RowResponse>
        PARSER = new com.google.protobuf.AbstractParser<RowResponse>() {
      @java.lang.Override
      public RowResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RowResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RowResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RowResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.urbcomp.cupid.db.spark.data.GrpcRemote.RowResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/proto/grpc_remote.p" +
      "roto\022\037org.urbcomp.cupid.db.spark.data\"2\n" +
      "\rSchemaRequest\022\r\n\005sqlId\030\001 \002(\t\022\022\n\nschemaJ" +
      "son\030\002 \002(\t\"\035\n\016SchemaResponse\022\013\n\003res\030\001 \001(\t" +
      "\"\033\n\nRowRequest\022\r\n\005sqlId\030\001 \002(\t\"\r\n\013RowResp" +
      "onse2\352\001\n\rRemoteService\022o\n\nsendSchema\022..o" +
      "rg.urbcomp.cupid.db.spark.data.SchemaReq" +
      "uest\032/.org.urbcomp.cupid.db.spark.data.S" +
      "chemaResponse\"\000\022h\n\007sendRow\022+.org.urbcomp" +
      ".cupid.db.spark.data.RowRequest\032,.org.ur" +
      "bcomp.cupid.db.spark.data.RowResponse\"\000(" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_urbcomp_cupid_db_spark_data_SchemaRequest_descriptor,
        new java.lang.String[] { "SqlId", "SchemaJson", });
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_urbcomp_cupid_db_spark_data_SchemaResponse_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_urbcomp_cupid_db_spark_data_RowRequest_descriptor,
        new java.lang.String[] { "SqlId", });
    internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_urbcomp_cupid_db_spark_data_RowResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
