version: "3.3"
services:
  spark-master:
    image: monokultur/cluster-apache-spark:3.0.2
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: monokultur/cluster-apache-spark:3.0.2
    ports:
      - "8081:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
#  spark-worker-b:
#    image: monokultur/cluster-apache-spark:3.0.2
#    ports:
#      - "8082:8080"
#      - "7001:7000"
#    depends_on:
#      - spark-master
#    environment:
#      - SPARK_MASTER=spark://spark-master:7077
#      - SPARK_WORKER_CORES=1
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_DRIVER_MEMORY=1G
#      - SPARK_EXECUTOR_MEMORY=1G
#      - SPARK_WORKLOAD=worker
#      - SPARK_LOCAL_IP=spark-worker-b
#    volumes:
#      - ./apps:/opt/spark-apps
#      - ./data:/opt/spark-data
  livy:
    image: livy:0.7.1
    ports:
      - "8998:8998"
    volumes:
    - ./apps:/opt/spark-apps
